apiVersion: v1
kind: Namespace
metadata:
  name: lunnoa-automate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: letsencrypt-pvc
  namespace: lunnoa-automate
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: lunnoa-automate
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "lunnoa-automate-server-core"
      containers:
        - name: lunnoa-automate-server-core
          image: ghcr.io/lunnoa-automate/server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9094
          envFrom:
            - secretRef:
                name: server-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 9094
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9094
            initialDelaySeconds: 30
            periodSeconds: 20
        - name: lunnoa-automate-server-core-nginx
          image: 699475920005.dkr.ecr.eu-central-1.amazonaws.com/server-core-nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: letsencrypt
              mountPath: /etc/letsencrypt
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
      volumes:
        - name: letsencrypt
          persistentVolumeClaim:
            claimName: letsencrypt-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: server-lb
  namespace: lunnoa-automate
  labels:
    app: server
spec:
  type: LoadBalancer
  selector:
    app: server
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443


