apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: lunnoa-automate
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: lunnoa-automate-ui
          image: ghcr.io/lunnoa-automate/ui:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ui-lb
  namespace: lunnoa-automate
  labels:
    app: ui
spec:
  type: LoadBalancer
  selector:
    app: ui
  ports:
    - name: http
      port: 80
      targetPort: 80


