-- AlterTable
ALTER TABLE "Agent" ADD COLUMN     "frequencyPenalty" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "maxRetries" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "maxTokens" INTEGER,
ADD COLUMN     "maxToolRoundTrips" INTEGER,
ADD COLUMN     "messageLookbackLimit" INTEGER,
ADD COLUMN     "presencePenalty" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "seed" INTEGER,
ADD COLUMN     "temperature" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN     "topP" DOUBLE PRECISION NOT NULL DEFAULT 1;
