const timezones = [
  { value: 'Pacific/Midway', label: 'GMT-11:00' },
  { value: 'America/Adak', label: 'GMT-10:00' },
  { value: 'America/Anchorage', label: 'GMT-09:00' },
  { value: 'Pacific/Gambier', label: 'GMT-09:00' },
  { value: 'America/Dawson_Creek', label: 'GMT-08:00' },
  { value: 'America/Ensenada', label: 'GMT-08:00' },
  { value: 'America/Los_Angeles', label: 'GMT-08:00' },
  { value: 'America/Chihuahua', label: 'GMT-07:00' },
  { value: 'America/Denver', label: 'GMT-07:00' },
  { value: 'America/Belize', label: 'GMT-06:00' },
  { value: 'America/Cancun', label: 'GMT-06:00' },
  { value: 'America/Chicago', label: 'GMT-06:00' },
  { value: 'Chile/EasterIsland', label: 'GMT-06:00' },
  { value: 'America/Bogota', label: 'GMT-05:00' },
  { value: 'America/Havana', label: 'GMT-05:00' },
  { value: 'America/New_York', label: 'GMT-05:00' },
  { value: 'America/Caracas', label: 'GMT-04:30' },
  { value: 'America/Campo_Grande', label: 'GMT-04:00' },
  { value: 'America/Glace_Bay', label: 'GMT-04:00' },
  { value: 'America/Goose_Bay', label: 'GMT-04:00' },
  { value: 'America/Santiago', label: 'GMT-04:00' },
  { value: 'America/La_Paz', label: 'GMT-04:00' },
  { value: 'America/Argentina/Buenos_Aires', label: 'GMT-03:00' },
  { value: 'America/Montevideo', label: 'GMT-03:00' },
  { value: 'America/Araguaina', label: 'GMT-03:00' },
  { value: 'America/Godthab', label: 'GMT-03:00' },
  { value: 'America/Miquelon', label: 'GMT-03:00' },
  { value: 'America/Sao_Paulo', label: 'GMT-03:00' },
  { value: 'America/St_Johns', label: 'GMT-03:30' },
  { value: 'America/Noronha', label: 'GMT-02:00' },
  { value: 'Atlantic/Cape_Verde', label: 'GMT-01:00' },
  { value: 'Europe/Belfast', label: 'GMT' },
  { value: 'Africa/Abidjan', label: 'GMT' },
  { value: 'Europe/Dublin', label: 'GMT' },
  { value: 'Europe/Lisbon', label: 'GMT' },
  { value: 'Europe/London', label: 'GMT' },
  { value: 'Africa/Algiers', label: 'GMT+01:00' },
  { value: 'Africa/Windhoek', label: 'GMT+01:00' },
  { value: 'Atlantic/Azores', label: 'GMT+01:00' },
  { value: 'Atlantic/Stanley', label: 'GMT+01:00' },
  { value: 'Europe/Amsterdam', label: 'GMT+01:00' },
  { value: 'Europe/Belgrade', label: 'GMT+01:00' },
  { value: 'Europe/Brussels', label: 'GMT+01:00' },
  { value: 'Africa/Cairo', label: 'GMT+02:00' },
  { value: 'Africa/Blantyre', label: 'GMT+02:00' },
  { value: 'Asia/Beirut', label: 'GMT+02:00' },
  { value: 'Asia/Damascus', label: 'GMT+02:00' },
  { value: 'Asia/Gaza', label: 'GMT+02:00' },
  { value: 'Asia/Jerusalem', label: 'GMT+02:00' },
  { value: 'Africa/Addis_Ababa', label: 'GMT+03:00' },
  { value: 'Asia/Riyadh', label: 'GMT+03:00' },
  { value: 'Europe/Minsk', label: 'GMT+03:00' },
  { value: 'Asia/Tehran', label: 'GMT+03:30' },
  { value: 'Asia/Dubai', label: 'GMT+04:00' },
  { value: 'Asia/Yerevan', label: 'GMT+04:00' },
  { value: 'Europe/Moscow', label: 'GMT+04:00' },
  { value: 'Asia/Kabul', label: 'GMT+04:30' },
  { value: 'Asia/Tashkent', label: 'GMT+05:00' },
  { value: 'Asia/Kolkata', label: 'GMT+05:30' },
  { value: 'Asia/Katmandu', label: 'GMT+05:45' },
  { value: 'Asia/Dhaka', label: 'GMT+06:00' },
  { value: 'Asia/Yekaterinburg', label: 'GMT+06:00' },
  { value: 'Asia/Rangoon', label: 'GMT+06:30' },
  { value: 'Asia/Bangkok', label: 'GMT+07:00' },
  { value: 'Asia/Novosibirsk', label: 'GMT+07:00' },
  { value: 'Asia/Hong_Kong', label: 'GMT+08:00' },
  { value: 'Asia/Krasnoyarsk', label: 'GMT+08:00' },
  { value: 'Australia/Perth', label: 'GMT+08:00' },
  { value: 'Australia/Eucla', label: 'GMT+08:45' },
  { value: 'Asia/Irkutsk', label: 'GMT+09:00' },
  { value: 'Asia/Seoul', label: 'GMT+09:00' },
  { value: 'Asia/Tokyo', label: 'GMT+09:00' },
  { value: 'Australia/Adelaide', label: 'GMT+09:30' },
  { value: 'Australia/Darwin', label: 'GMT+09:30' },
  { value: 'Pacific/Marquesas', label: 'GMT+09:30' },
  { value: 'Australia/Brisbane', label: 'GMT+10:00' },
  { value: 'Australia/Hobart', label: 'GMT+10:00' },
  { value: 'Asia/Yakutsk', label: 'GMT+10:00' },
  { value: 'Australia/Lord_Howe', label: 'GMT+11:00' },
  { value: 'Asia/Vladivostok', label: 'GMT+11:00' },
  { value: 'Pacific/Norfolk', label: 'GMT+11:30' },
  { value: 'Asia/Anadyr', label: 'GMT+12:00' },
  { value: 'Asia/Magadan', label: 'GMT+12:00' },
  { value: 'Pacific/Auckland', label: 'GMT+12:00' },
  { value: 'Pacific/Chatham', label: 'GMT+12:45' },
  { value: 'Pacific/Tongatapu', label: 'GMT+13:00' },
  { value: 'Pacific/Kiritimati', label: 'GMT+14:00' },
];

//Export timezone list, but filter so that not every timezone is included. Group them a little bit. Return an array of value, select
export const timezoneDropdown = timezones.map((tz) => {
  return {
    value: tz.value,
    label: `(${tz.label}) ${tz.value}`,
  };
});
